os: linux
language: cpp
sudo: required
dist: trusty
compiler:
    - gcc

before_script:
    - a=`pwd`
    - sudo add-apt-repository -y --allow-unauthenticated ppa:krzysztof-trzepla/onedata
    - sudo add-apt-repository -y --allow-unauthenticated ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install -qq gcc-5
    - sudo apt-get install -qq git
    - export CXX="g++-5"
    - export CC="gcc-5"
    - sudo apt-get install -qq libtbb-dev=4.4~20151115-0ubuntu3ppa1~trusty libtbb2=4.4~20151115-0ubuntu3ppa1~trusty libtbb2-dbg=4.4~20151115-0ubuntu3ppa1~trusty libgtest-dev
    - cd $a
    - mkdir build
    - cd build

script:
    - cmake -DBUILD_MEMSAVE=OFF -DBUILD_TEST=ON -DBUILD_DEMO=ON .. && make && ./mapmap_test
    - cmake -DBUILD_MEMSAVE=ON -DBUILD_TEST=ON -DBUILD_DEMO=ON .. && make && ./mapmap_test

